In [1]:
import pandas as pd
import numpy as np

In [2]:
df_icu = pd.read_csv('D:\Thesis\exports\o31_ICU_final.csv')

In [3]:
df_1 = df_icu.iloc[:107568,:]
df_2 = df_icu.iloc[107568:,:]

In [4]:
df_1.tail()

,Department,subject_id,hadm_id,date,time,Heart Rate (bpm),Respiratory Rate (insp/min),O2 saturation pulseoxymetry (%),Non Invasive Blood Pressure mean (mmHg),Non Invasive Blood Pressure systolic (mmHg),...,CD19 Absolute Count (Blood),CD20 % (Blood),CD20 Absolute Count (Blood),Promyelocytes (Pleural),CD19 (Other Body Fluid),CD3 (Other Body Fluid),CD34 (Other Body Fluid),"Bicarbonate, Stool (Stool)",Non-squamous Epithelial Cells (Urine),hospital_expire_flag
107563,ICU,16934201,20511019,2145-03-01,00:00:00,81.75,21.000,96.75,90.50,127.250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107564,ICU,16934201,20511019,2145-03-01,08:00:00,80.00,23.375,97.50,86.75,113.625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107565,ICU,16934201,20511019,2145-03-01,16:00:00,78.50,23.500,94.75,69.75,106.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107566,ICU,16934201,20511019,2145-03-02,08:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107567,ICU,16934201,20511019,2145-03-03,00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival

In [5]:
df_2.head()

,Department,subject_id,hadm_id,date,time,Heart Rate (bpm),Respiratory Rate (insp/min),O2 saturation pulseoxymetry (%),Non Invasive Blood Pressure mean (mmHg),Non Invasive Blood Pressure systolic (mmHg),...,CD19 Absolute Count (Blood),CD20 % (Blood),CD20 Absolute Count (Blood),Promyelocytes (Pleural),CD19 (Other Body Fluid),CD3 (Other Body Fluid),CD34 (Other Body Fluid),"Bicarbonate, Stool (Stool)",Non-squamous Epithelial Cells (Urine),hospital_expire_flag
107568,ICU,16934248,27504332,2142-04-17,00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107569,ICU,16934248,27504332,2142-04-17,16:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107570,ICU,16934248,27504332,2142-04-18,00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107571,ICU,16934248,27504332,2142-04-19,00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival
107572,ICU,16934248,27504332,2142-04-19,08:00:00,64.0,14.0,94.0,98.0,148.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,survival

In [6]:
df_1.to_csv('D:\Thesis\exports\Train_test\Train_70.csv', index=False)
df_2.to_csv('D:\Thesis\exports\Train_test\Test_30.csv', index=False)