In [1]:
import pandas as pd

In [2]:
df_chart_tbl = pd.read_csv('D:\Papers\Cyprus_Paper\Data\o14_empty_chart_min_tbl.csv', index_col=False)
df_min_chart = pd.read_csv('D:\Papers\Cyprus_Paper\Data\o9_chartevent_24_hour_min.csv', index_col=False)
df_data_chart = pd.read_csv('D:\MSc Aegean\Thesis\mimic-iv-1.0\icu\d_items.csv.gz')

In [3]:
"""
Δημιουργώ εκ νέου την στήλη concat
χωρίς κενά ανάμεσα στα στοιχεία.
Θα χρησιμοποιήσω αυτή τη στήλη σαν
index γιατί τα κενά μπορεί να
δημιουργήσουν πρόβλημα.
"""
df_chart_tbl["concat"] = (df_chart_tbl["subject_id"].astype(str)
                          + df_chart_tbl["hadm_id"].astype(str)
                          + df_chart_tbl["charttime"].astype(str))

"""
Αφαιρώ τους χαρακτήρες - και :
από της τιμές της concat για να
αποφύγω πιθανά προβλήματα
"""
df_chart_tbl['concat'] = df_chart_tbl['concat'].str.replace('-','')
df_chart_tbl['concat'] = df_chart_tbl['concat'].str.replace(':','')

In [4]:
# Ορίζω την στήλη concat ως index των γραμμών
df_chart_tbl = df_chart_tbl.set_index('concat')

In [5]:
"""
Δημιουργώ την στήλη concat και στον πίνακα
που περιλαμβάνει τις μετρήσεις για να είναι
το κοινό σημείο ανάμεσα στους δυο πίνακες
"""
df_min_chart["concat"] = (df_min_chart["subject_id"].astype(str)
                           + df_min_chart["hadm_id"].astype(str)
                           + df_min_chart["charttime"].astype(str))


"""
Αφαιρώ τους χαρακτήρες - και :
από της τιμές της concat για να
αποφύγω πιθανά προβλήματα
"""
df_min_chart['concat'] = df_min_chart['concat'].str.replace('-','')
df_min_chart['concat'] = df_min_chart['concat'].str.replace(':','')

In [6]:
# Γεμίζω τον πίνακα
for row in df_min_chart.itertuples():
    con = row.concat
    item = row.itemid
    value = row.Min_Chart
    df_chart_tbl.at['{}'.format(con), '{}'.format(item)] = value

In [7]:
# Αποθήκευση του τελικού αρχείου με επικεφαλίδες τους κωδικούς των παρατηρήσεων
df_chart_tbl.to_csv('D:\Papers\Cyprus_Paper\Data\o19_fill_chart_min_itemid_header_tbl.csv', index=False)

In [8]:
df_data_chart = df_data_chart.set_index('itemid')

In [10]:
# Ενοποίηση τιμών σε κελιά
df_data_chart["header"] = ("Min - "
                           + df_data_chart["label"].astype(str)
                           + " ("
                           + df_data_chart["unitname"].astype(str)
                           + ")")

In [11]:
"""
Ελέγχω τις κεφαλίδες και αν δεν ανήκουν στις
τέσσερις πρώτες τιμές κάνω τις αντικατάσταση.
"""
for col in df_chart_tbl.columns:
    if ((col != 'subject_id') and
        (col != 'hadm_id') and
        (col != 'charttime')):
        temp = (df_data_chart.loc[int(col), 'header'])
        df_chart_tbl.rename(columns={'{}'.format(col): '{}'.format(temp)}, inplace=True)

In [12]:
df_chart_tbl

,subject_id,hadm_id,charttime,Min - Heart Rate (bpm),Min - Respiratory Rate (insp/min),Min - O2 saturation pulseoxymetry (%),Min - Non Invasive Blood Pressure systolic (mmHg),Min - Non Invasive Blood Pressure diastolic (mmHg),Min - Non Invasive Blood Pressure mean (mmHg),Min - Arterial Blood Pressure mean (mmHg),...,Min - Resistance (cmH2O/L/seconds),Min - ABI Ankle BP L (mmHg),Min - ABI Brachial BP R (mmHg),Min - ITBVI (PiCCO) (mL/m2),Min - Patient/Family Informed_V1 (nan),Min - Pheresis Catheter Line Tip Cultured (nan),Min - Triple Introducer Line Tip Cultured (nan),Min - Depth at which wedge obtained (PA Line) (cm),Min - Clot Size (cm) (cm),Min - Resting Energy Expenditure (kcal/day)
concat,,,,,,,,,,,,,,,,,,,,,
100047332741187621741204,10004733,27411876,2174-12-04,87.0,16.0,94.0,124.0,75.0,90.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741205,10004733,27411876,2174-12-05,75.0,8.0,90.0,108.0,50.0,65.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741206,10004733,27411876,2174-12-06,70.0,8.0,93.0,108.0,60.0,70.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741207,10004733,27411876,2174-12-07,65.0,10.0,93.0,121.0,68.0,78.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741208,10004733,27411876,2174-12-08,71.0,15.0,92.0,147.0,89.0,104.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994422678531721481125,19999442,26785317,2148-11-25,46.0,9.0,95.0,124.0,67.0,82.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199994422678531721481126,19999442,26785317,2148-11-26,48.0,11.0,97.0,133.0,71.0,85.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451102,19999987,23865745,2145-11-02,94.0,21.0,98.0,115.0,70.0,81.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451103,19999987,23865745,2145-11-03,76.0,14.0,93.0,90.0,57.0,65.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451104,19999987,23865745,2145-11-04,87.0,14.0,91.0,100.0,51.0,60.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Αποθήκευση του τελικού αρχείου με επικεφαλίδες τις ονομασίες των παρατηρήσεων
df_chart_tbl.to_csv('D:\Papers\Cyprus_Paper\Data\o20_fill_min_chart_label_header_tbl.csv', index=False)