In [1]:
import pandas as pd

In [2]:
df_chart_tbl = pd.read_csv('D:\Papers\Cyprus_Paper\Data\o32_empty_lab_min_tbl.csv', index_col=False)
df_mean_chart = pd.read_csv('D:\Papers\Cyprus_Paper\Data\o27_labevents_24_hour_min.csv', index_col=False)
df_data_chart = pd.read_csv('D:\MSc Aegean\Thesis\mimic-iv-1.0\hosp\d_labitems.csv.gz')

In [3]:
"""
Δημιουργώ εκ νέου την στήλη concat
χωρίς κενά ανάμεσα στα στοιχεία.
Θα χρησιμοποιήσω αυτή τη στήλη σαν
index γιατί τα κενά μπορεί να
δημιουργήσουν πρόβλημα.
"""
df_chart_tbl["concat"] = (df_chart_tbl["subject_id"].astype(str)
                          + df_chart_tbl["hadm_id"].astype(str)
                          + df_chart_tbl["charttime"].astype(str))

"""
Αφαιρώ τους χαρακτήρες - και :
από της τιμές της concat για να
αποφύγω πιθανά προβλήματα
"""
df_chart_tbl['concat'] = df_chart_tbl['concat'].str.replace('-','')
df_chart_tbl['concat'] = df_chart_tbl['concat'].str.replace(':','')

In [4]:
# Ορίζω την στήλη concat ως index των γραμμών
df_chart_tbl = df_chart_tbl.set_index('concat')

In [5]:
"""
Δημιουργώ την στήλη concat και στον πίνακα
που περιλαμβάνει τις μετρήσεις για να είναι
το κοινό σημείο ανάμεσα στους δυο πίνακες
"""
df_mean_chart["concat"] = (df_mean_chart["subject_id"].astype(str)
                           + df_mean_chart["hadm_id"].astype(str)
                           + df_mean_chart["charttime"].astype(str))


"""
Αφαιρώ τους χαρακτήρες - και :
από της τιμές της concat για να
αποφύγω πιθανά προβλήματα
"""
df_mean_chart['concat'] = df_mean_chart['concat'].str.replace('-','')
df_mean_chart['concat'] = df_mean_chart['concat'].str.replace(':','')

In [6]:
# Γεμίζω τον πίνακα
for row in df_mean_chart.itertuples():
    con = row.concat
    item = row.itemid
    value = row.Min_Lab
    df_chart_tbl.at['{}'.format(con), '{}'.format(item)] = value

In [7]:
# Αποθήκευση του τελικού αρχείου με επικεφαλίδες τους κωδικούς των παρατηρήσεων
df_chart_tbl.to_csv('D:\Papers\Cyprus_Paper\Data\o37_fill_lab_min_itemid_header_tbl.csv', index=False)

In [8]:
df_data_chart = df_data_chart.set_index('itemid')

In [9]:
# Ενοποίηση τιμών σε κελιά
df_data_chart["header"] = ("Min - "
                           + df_data_chart["label"].astype(str)
                           + " ("
                           + df_data_chart["fluid"].astype(str)
                           + ")")

In [10]:
"""
Ελέγχω τις κεφαλίδες και αν δεν ανήκουν στις
τέσσερις πρώτες τιμές κάνω τις αντικατάσταση.
"""
for col in df_chart_tbl.columns:
    if ((col != 'subject_id') and
        (col != 'hadm_id') and
        (col != 'charttime')):
        temp = (df_data_chart.loc[int(col), 'header'])
        df_chart_tbl.rename(columns={'{}'.format(col): '{}'.format(temp)}, inplace=True)

In [14]:
df_chart_tbl

,subject_id,hadm_id,charttime,Min - Potassium (Blood),Min - Creatinine (Blood),Min - Urea Nitrogen (Blood),Min - Chloride (Blood),Min - Sodium (Blood),Min - Bicarbonate (Blood),Min - Anion Gap (Blood),...,Min - Myelocytes (Cerebrospinal Fluid),Min - Promyelocytes (Pleural),Min - Non-squamous Epithelial Cells (Urine),Min - RBC Casts (Urine),Min - L (Blood),Min - Young Cells (Blood),Min - NRBC (Joint Fluid),Min - H (Blood),Min - DHEA-Sulfate (Blood),"Min - Cholesterol, Ascites (Ascites)"
concat,,,,,,,,,,,,,,,,,,,,,
100047332741187621741204,10004733,27411876,2174-12-04,3.4,3.4,44.0,108.0,144.0,24.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741205,10004733,27411876,2174-12-05,3.4,3.3,40.0,106.0,143.0,20.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741206,10004733,27411876,2174-12-06,3.8,3.8,40.0,106.0,143.0,24.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741207,10004733,27411876,2174-12-07,4.2,3.7,38.0,108.0,144.0,22.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100047332741187621741208,10004733,27411876,2174-12-08,4.6,3.4,37.0,110.0,145.0,20.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199999872386574521451104,19999987,23865745,2145-11-04,4.1,1.2,22.0,114.0,147.0,26.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451105,19999987,23865745,2145-11-05,3.6,0.9,19.0,110.0,145.0,27.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451106,19999987,23865745,2145-11-06,3.7,1.0,14.0,109.0,143.0,27.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451109,19999987,23865745,2145-11-09,3.4,0.9,8.0,109.0,144.0,26.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199999872386574521451107,19999987,23865745,2145-11-07,4.0,0.9,8.0,108.0,145.0,27.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Αποθήκευση του τελικού αρχείου με επικεφαλίδες τις ονομασίες των παρατηρήσεων
df_chart_tbl.to_csv('D:\Papers\Cyprus_Paper\Data\o38_fill_min_lab_label_header_tbl.csv', index=False)