In [ ]:
"""
Γεμίζω τον πίνακα με τις μετρήσεις
του labevent 8ώρου.

Ο πίνακας μου απαρτίζεται από 340 στήλες και 34341 γραμμές,
οπότε μου δημιουργούν 11.675.940 κελιά.

Οι τιμές μου ανέρχονται στα 569.340 οπότε με μια αφαίρεση
προκείπτουν 11.106.600 NaN κελιά, πράγμα που επιβεβαιώνει
και η εντολή df_lab_tbl.isna().sum().sum()

"""

In [2]:
import pandas as pd

In [3]:
df_lab_tbl = pd.read_csv('D:\Thesis\exports\o26_hosp_empty_lab_tbl.csv', index_col = False)
df_data_labevents = pd.read_csv('D:\Thesis\mimic-iv-1.0\hosp\d_labitems.csv.gz')
df_mean_lab = pd.read_csv('D:\Thesis\exports\o25_hosp_labevents_grouped_8hours_date_time.csv')

In [4]:
# Φέρνω τις τελευταίες στήλες, πρώτες
for i in range (1, 5):
    cols = list(df_lab_tbl.columns)
    cols = [cols[-1]] + cols[:-1]
    df_lab_tbl = df_lab_tbl[cols]

In [5]:
# Ελέγχω αν υπάρχει NaN στην στήλη με τις μέσες τιμές, το αποτέλεσμα ισούται με μηδέν.
df_mean_lab['Mean_Lab'].isna().sum()

0

In [6]:
"""
Δημιουργώ εκ νέου την στήλη concat χωρίς
κενά ανάμεσα στα στοιχεία. Θα χρησιμοποιήσω
αυτή τη στήλη σαν index και τα κενά μπορεί
να δημιουργήσουν πρόβλημα.
"""
df_lab_tbl["concat"] = (df_lab_tbl["subject_id"].astype(str)
                          + df_lab_tbl["hadm_id"].astype(str)
                          + df_lab_tbl["date"].astype(str)
                          + df_lab_tbl["time"].astype(str))

# Αφαιρώ τους χαρακτήρες - και : από της τιμές της concat
df_lab_tbl['concat'] = df_lab_tbl['concat'].str.replace('-','')
df_lab_tbl['concat'] = df_lab_tbl['concat'].str.replace(':','')

# Ορίζω την στήλη concat ως index των γραμμών
df_lab_tbl = df_lab_tbl.set_index('concat')

In [7]:
"""
Δημιουργώ την στήλη concat και στον πίνακα
που περιλαμβάνει τις μετρήσεις για να είναι
το κοινό σημείο ανάμεσα στους δυο πίνακες.
"""
df_mean_lab["concat"] = (df_mean_lab["subject_id"].astype(str)
                         + df_mean_lab["hadm_id"].astype(str)
                         + df_mean_lab["date"].astype(str)
                         + df_mean_lab["time"].astype(str))

# Αφαιρώ τους χαρακτήρες - και : από της τιμές της concat
df_mean_lab['concat'] = df_mean_lab['concat'].str.replace('-','')
df_mean_lab['concat'] = df_mean_lab['concat'].str.replace(':','')

In [8]:
for row in df_mean_lab.itertuples():
    con = row.concat
    item = row.itemid
    value = row.Mean_Lab
    df_lab_tbl.at['{}'.format(con), '{}'.format(item)] = value

In [9]:
# Έλεγχος NaN περιοχών σε όλο το dataframe
df_lab_tbl.isna().sum().sum()

11106600

In [10]:
df_lab_tbl

,subject_id,hadm_id,date,time,50801,50802,50803,50804,50805,50806,...,52272,52278,52281,52283,52285,52286,52312,52369,52391,52769
concat,,,,,,,,,,,,,,,,,,,,,
100018772567929221490522080000,10001877,25679292,2149-05-22,08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490523000000,10001877,25679292,2149-05-23,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490522000000,10001877,25679292,2149-05-22,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490524000000,10001877,25679292,2149-05-24,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490524160000,10001877,25679292,2149-05-24,16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199955932723880421101119000000,19995593,27238804,2110-11-19,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640725000000,19999840,26071774,2164-07-25,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640724160000,19999840,26071774,2164-07-24,16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640727160000,19999840,26071774,2164-07-27,16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640728000000,19999840,26071774,2164-07-28,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Αποθήκευση του τελικού αρχείου με επικεφαλίδες τους κωδικούς των παρατηρήσεων
df_lab_tbl.to_csv('D:\Thesis\exports\o27_hosp_fill_lab_itemid_header_tbl.csv', index=False)

## Αντικατάσταση των κεφαλίδων

In [12]:
df_data_labevents = df_data_labevents.set_index('itemid')

In [13]:
# Ενοποίηση τιμών σε κελιά
df_data_labevents["header"] = (df_data_labevents["label"].astype(str)
                                                + " ("
                                                + df_data_labevents["fluid"].astype(str)
                                                + ")")

In [14]:
"""
Ελέγχω τις κεφαλίδες και αν δεν ανήκουν στις
τέσσερις πρώτες τιμές κάνω τις αντικαταστάσεις.
"""
for col in df_lab_tbl.columns:
    if ((col != 'subject_id')
        and (col != 'hadm_id')
        and (col != 'date')
        and (col != 'time')):
        temp = (df_data_labevents.loc[int(col), 'header'])
        df_lab_tbl.rename(columns={'{}'.format(col): '{}'.format(temp)}, inplace=True)

In [15]:
df_lab_tbl

,subject_id,hadm_id,date,time,Alveolar-arterial Gradient (Blood),Base Excess (Blood),"Calculated Bicarbonate, Whole Blood (Blood)",Calculated Total CO2 (Blood),Carboxyhemoglobin (Blood),"Chloride, Whole Blood (Blood)",...,Monocytes (Cerebrospinal Fluid),Other (Cerebrospinal Fluid),Polys (Cerebrospinal Fluid),Promyelocytes (Cerebrospinal Fluid),"RBC, CSF (Cerebrospinal Fluid)","Total Nucleated Cells, CSF (Cerebrospinal Fluid)","Total Nucleated Cells, Joint (Joint Fluid)","Total Nucleated Cells, Other (Other Body Fluid)","Total Nucleated Cells, Pleural (Pleural)",Absolute Lymphocyte Count (Blood)
concat,,,,,,,,,,,,,,,,,,,,,
100018772567929221490522080000,10001877,25679292,2149-05-22,08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490523000000,10001877,25679292,2149-05-23,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490522000000,10001877,25679292,2149-05-22,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490524000000,10001877,25679292,2149-05-24,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100018772567929221490524160000,10001877,25679292,2149-05-24,16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199955932723880421101119000000,19995593,27238804,2110-11-19,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640725000000,19999840,26071774,2164-07-25,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640724160000,19999840,26071774,2164-07-24,16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640727160000,19999840,26071774,2164-07-27,16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998402607177421640728000000,19999840,26071774,2164-07-28,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#Εισάγω στήλη με την τιμές την ονομασία του τμήματος
df_lab_tbl.insert(0, "Department", "HOSP")

In [17]:
# Αποθήκευση του τελικού αρχείου με επικεφαλίδες τα label των παρατηρήσεων
df_lab_tbl.to_csv('D:\Thesis\exports\o28_hosp_fill_lab_label_header_tbl.csv', index=False)